### ISSUE TITLE
Lecture2 exercise

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [MuhammadSulaiman001/prolog-lab#2]
Exercise1:

The term in Fibonacci Series is defined as the sum of the previous 2 terms' values, i.e 1,1,2,3,5,8,13,..

Define fib/2, where the first parameter is the term index (starts from 1), the second parameter is the term value. 

    % Sample Queries:
    ?- fib(4, Res)
        Res = 3
    ?- fib(5, Res)
        Res = 5
    ?- fib(6, Res)
        Res = 8

Exercise2:

Given a directed graph like the following:

    % facts
    link(node1, node2).
    link(node1, node3).
    link(node2, node3).
    link(node2, node5).
    link(node2, node6).
    
Define connection_valid/2, to check if there is a connection between two nodes.

    % Sample Queries:
    ?- connection_valid(node1, node6).
        true
    ?- connection_valid(node3, node5).
        false

**Comment by YamanQD** [comment]
<details>
  <summary>Exercise1 solution</summary>

  ```prolog
fib(0, 1).
fib(1, 1).
fib(X, Res):- X > 0, X1 is X-1, fib(X1, Res1), X2 is X1-1, fib(X2, Res2), Res is Res1 + Res2.

% Query Examples:

% ?- fib(0, Res).
% Res = 1.

% ?- fib(2, Res).
% Res = 2.

% ?- fib(4, Res).
% Res = 5.

% ?- fib(6, Res).
% Res = 13.
  ```
  
</details>

<details>
  <summary>Exercise2 solution</summary>

  ```prolog
% facts
link(node1, node2).
link(node1, node3).
link(node2, node3).
link(node2, node5).
link(node2, node6).

connection_valid(X, Y) :- link(X, Y).
connection_valid(X, Y) :- link(X, Z), link(Z, Y).

% Query Examples:

% ?- connection_valid(node6, node3).
% false.

% ?- connection_valid(node1, node3).
% true.

% ?- connection_valid(node1, node6).
% true.

% ?- connection_valid(node6, node1).
% false.
  ```
  Note: If this were to be an unweighted graph:
```prolog
% facts
link(node1, node2).
link(node1, node3).
link(node2, node3).
link(node2, node5).
link(node2, node6).

% 1 -> 2 if 1 -> 2
connection_valid(X, Y) :- link(X, Y).
% 2 -> 1 if 1 -> 2
connection_valid(X, Y) :- link(Y, X).
% 1 -> 3 if 1 -> 2 -> 3
connection_valid(X, Y) :- link(X, Z), link(Z, Y).
% 3 -> 1 if 1 -> 2 -> 3
connection_valid(X, Y) :- link(Y, Z), link(Z, X).
% 1 -> 3 if 2 -> 1 and 2 -> 3
% 3 -> 1 if 2 -> 1 and 2 -> 3
connection_valid(X, Y) :- link(Z, Y), link(Z, X).

% Query Examples:

% ?- connection_valid(node3, node1).
% true.

% ?- connection_valid(node1, node3).
% true.

% ?- connection_valid(node4, node3).
% false.

% ?- connection_valid(node1, node6).
% true.

% ?- connection_valid(node6, node1).
% true.

% ?- connection_valid(node5, node6).
% true.
```
</details>
