### ISSUE TITLE
Add a new learning resource

### ISSUE THREAD

**Issue by HasanMothaffar** [MuhammadSulaiman001/prolog-lab#3]
Al Salam Alaikum Muhammad,

I was watching a talk today about Yarn Berry, a package manager for JavaScript projects, when I learned that it ships a new feature called `constraints`. It's a useful feature that helps you enforce rules that you specify over the dependencies of your project's workspaces.

Anyway, I was surprised to learn that this feature utilizes **Prolog** to specify the rules! So I thought maybe we could add a link to this feature in the learning resources of this repository? It felt really great that I'm learning something at university that is used in *real* projects out in the world, so I wanted to share this with other students.

**References:**
- A Medium article that explains this feature: https://medium.com/swlh/creating-and-using-yarn-constraints-2464ba46482a
- Talk link: https://youtu.be/UxrwfTchPJ8?t=425
- Yarn Berry's constraints: https://yarnpkg.com/features/constraints

**Comment by Rami-Sabbagh** [comment]
Hey Hasan,
You caught my interest with this!

SWI-Prolog wasn't so encouraging to use. As it felt like old software with bloated features (like the editor).
But seeing prolog being used in Yarn provoked my curiosity on how that is done.

So I instantly went and dug through the source-code of it and found the engine they use:

https://github.com/yarnpkg/berry/blob/e81618d8bc98c17b7b9700bac0f9902bebeb259f/packages/plugin-constraints/package.json#L15

Which is a plain JS library `tau-prolog`!
- [NPM Package](https://www.npmjs.com/package/tau-prolog).
- [Website](http://tau-prolog.org/).
- [Playground](http://tau-prolog.org/sandbox/).
- [Source-code](https://github.com/tau-prolog/tau-prolog).

This open a whole new range of prolog applications. As it can be now integrated in any JS project!
And even used in anyone's browsers.

Speaking of integration, isn't this one of Muhammad's goals? 😏 

https://github.com/MuhammadSulaiman001/prolog-lab/blob/50b578075ed2f5e656c345d5b4dd042aa5921a45/res/supplementaries.md?plain=1#L25

**Comment by Rami-Sabbagh** [comment]
Here's a nice example of the [Knight's tour problem](https://en.wikipedia.org/wiki/Knight%27s_tour) implemented using `tau-prolog`:
http://tau-prolog.org/examples/knights-tour

![image](https://user-images.githubusercontent.com/6272475/166258900-2062e857-64f4-41c3-884a-bd3c7cb3e698.png)

**Comment by MuhammadSulaiman001** [comment]
> Anyway, I was surprised to learn that this feature utilizes **Prolog** to specify the rules! So I thought maybe we could add a link to this feature in the learning resources of this repository? It felt really great that I'm learning something at university that is used in _real_ projects out in the world, so I wanted to share this with other students.


Peace be upon you @HasanMothaffar, thank you so much for the suggestion, this is great.. 

Actually, the title says it all, and as @Rami-Sabbagh mentioned in his comment.. I want to enrich the material and give the students an insight on how Prolog can be used to end up with a product-like deliverable.

My intent was to ask the students to make a presentation/demo on how they can integrate .pl code in a desktop (web, mobile, ..) application.. that being said, would you mind collaborate on this? I will make an announcement about this in the next lecture, God willing..

**Comment by MuhammadSulaiman001** [comment]
> SWI-Prolog wasn't so encouraging to use. As it felt like old software with bloated features (like the editor)

Hi @Rami-Sabbagh, you might be taking about the editor that comes along with SWI-Prolog, I defiantly agree with you (so I have never used it).

Anyway, the command-line interface is super necessary, the text editor can be anything of your choice, I encourage you to look for the best tools (text editor, command line) that can boost the productivity of the developer (something that provides code formatting, code completion, syntax highlighting, etc...) and introduce such a tech for me and the students in a small talk in the next lecture or the one after the next.

Personally, I suggest Visual Studio Code with [VSC-Prolog](https://marketplace.visualstudio.com/items?itemName=arthurwang.vsc-prolog) which provides a full code linting, however, the door is always open to bring any tech out there into the table.

**Comment by Rami-Sabbagh** [comment]
Hi @MuhammadSulaiman001,
Yes sure I can do a small research on the tooling for prolog!
And for the integration topic, also why not? I just hope that I could find enough time :)
