### ISSUE TITLE
Lecture3 Revisited

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [MuhammadSulaiman001/prolog-lab#4]
Suppose we have the following dialogue:

```
Ahmad says: "I do nothing"
Dan says: "I do nothing"
Bassel says: "Dan is guilty"
Camal says: "Bassel is guilty"
```

Knowing that only one of them is honest, fix the following code to figure out who is the guilty one..

```
guilty(Guilty):-
    member(Guilty, [ahmad, bassel, camal, dan]),
    (Guilty = ahmad -> Ahmad =1; Ahmad =0),
    (Guilty = dan  -> Bassel =1; Bassel =0),
    (Guilty = bassel  -> Camal =1; Camal =0),
    (Guilty \= dan -> Dan =1; Dan = 0),
    Ahmad + Bassel + Camal + Dan =:= 1, !.
```

Note: `(if -> then; else)` syntax is explained in [Utilities.md](../blob/master/Utilities.md)

Test your edit by executing `?- guilty(G).` in command line.

**Comment by Rami-Sabbagh** [comment]
Here's the fixed version:


<details>
<summary>A possible solution (click to reveal)</summary>

```prolog
guilty(Guilty):-
    % One of them is guilty.
    member(Guilty, [ahmad, bassel, camal, dan]),

    % check for honesty vs lies
    % 0 for being a liar, 1 for being honest.

    % (Ahmad says: "I did nothing")
    % 0: liar => he is guilty.
    % 1: honest => he is not guilty.
    (Guilty = ahmad -> Ahmad =0; Ahmad =1),

    % (Dan says: "I did nothing")
    % 0: liar => he is guilty.
    % 1: honest => he is not guilty.
    (Guilty = dan  -> Dan =0; Dan =1),

    % (Bassel says: "Dan is guilty").
    % 0: liar => dan is not guilty.
    % 1: honset => dan is guilty.
    (Guilty \= dan -> Bassel =0; Bassel =1),

    % (Camal says: "Bassel is guilty").
    % 0: liar => bassel is not guilty.
    % 1: honset => bassel is guilty.
    (Guilty \= bassel -> Camal =0; Camal =1),

    % (only one of them is honest, others are liars).
    Ahmad + Bassel + Camal + Dan =:= 1, !.
```

Note that the problem has 2 dimensions: `guilty vs innocent` and `honest vs liar`.

## Execution:

```prolog
?- guilty(G).
%  G = ahmad.
```

</details>

Have a nice day!

**Comment by OmamaEwer** [comment]
guilty(Guilty):-
    member(Guilty, [ahmad, bassel, camal, dan]),
    (Guilty \= ahmad -> Ahmad =1; Ahmad =0),
    (Guilty = dan  -> Bassel =1; Bassel =0),
    (Guilty = bassel  -> Camal =1; Camal =0),
    (Guilty \= dan -> Dan =1; Dan = 0),
    Ahmad + Bassel + Camal + Dan =:= 1, !.

**Comment by OmamaEwer** [comment]
`guilty(Guilty):-
    member(Guilty, [ahmad, bassel, camal, dan]),
    (Guilty \= ahmad -> Ahmad =1; Ahmad =0),
    (Guilty = dan  -> Bassel =1; Bassel =0),
    (Guilty = bassel  -> Camal =1; Camal =0),
    (Guilty \= dan -> Dan =1; Dan = 0),
    Ahmad + Bassel + Camal + Dan =:= 1, !.`

**Comment by MuhammadSulaiman001** [comment]
Hi guys, both solutions are correct.. the issue was on this line `(Guilty = ahmad -> Ahmad =1; Ahmad =0)`
@Rami-Sabbagh flips the `then; else`,
@OmamaEwer negates the `if` conditions, which is the preferable fix, bcz it will reflect what Ahmad was saying in the dialogue, as the other cases reflect what was being said in the dialogue :thumbsup:
