### ISSUE TITLE
Lecture5 TODOs

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [MuhammadSulaiman001/prolog-lab#6]
01. `is_even_length/1`
02. `sum_items_values/2`
03. `get_last_element/2`
04. `get_last_but_one/2`
05. `count_elements_less_than/3`
06. `get_max/2`
07. `get_element_at_position/3`
08. `insert_element_into_position/3` % index starts from 0
09. `split_at_index/4`
10. `duplicate_elements/2` % repeat the same element in-place
11. `remove_duplicates/2` % convert the list into a set (no item repetition)
12. `get_union/3`
13. `get_intersection/3`
14. `my_reverse/2`
15. `is_symmetric/1`

Note: I will leave the task of verifying your code up to you.. so this thread will stay open for a while ⏳

**Comment by OmamaEwer** [comment]
`is_even_length([]). 
`
`is_even_length([H|T]):- length([H|T],L), 0 is L mod 2.
`
*******************************************************
`sum_items_values([],0).
`
`sum_items_values([H|T],S):- sum_items_values(T,S1),S is H+S1.
`
*******************************************************
`get_last_element([],[]).
`
`get_last_element([X],X).
`
`get_last_element([H|L],Last):-  get_last_element(L,Last).
`
*******************************************************
`get_last_but_one([X,Y],X).
`
`get_last_but_one([],[]).
`
`get_last_but_one([H|L],Z):- get_last_but_one(L,Z).
`
*******************************************************

*******************************************************
`get_max([],[]).
`
`get_max([X],X).`
`get_max([H|T],X):- get_max(T,Y),(H>Y -> X=H;X=Y).
`
*******************************************************
`get_element_at_position([],P,_).
`
`get_element_at_position([H|T],1,H).
`
`get_element_at_position([H|T],P,E):- length([H|T],L),P=<L, P1 is P-1, get_element_at_position(T,P1,E).
`
*******************************************************
`%insert_element_into_position:`
`nt([],X,P,[X]).`
`nt([H|T],X,0,[X,H|T]).
`
`nt([H|T],X,P,[H|Y]):-P>=0, P1 is P-1, nt(T,X,P1,Y).
`
*******************************************************
`split_at_index([],I,[],[]).`
`split_at_index([H|T],0,[H], T).
`
`split_at_index([H|Y],I,[H|Z],W):- I>=0,I1 is I-1,split_at_index(Y,I1,Z,W).
`
*******************************************************
`duplicate_items([],[]).`
`duplicate_items([X],[X,X]).
`
`duplicate_items([H|T],[H,H|Res]):- duplicate_items(T,Res).
`
% p.s. we already took  duplicate_elements/2  &  remove_duplicates/2 in the class
*******************************************************

*******************************************************
`get_union([],L,L).`
`get_union([X],[Y],[X,Y]).`
`get_union([H1|T1],List2,[H1|List]):- get_union(T1,List2,List).
`
*******************************************************
`reverse([],[]).
`
`reverse([X],[X]).`
`reverse([X,Y],[Y,X]).`
`reverse([H|T],[T|H]):-reverse(T,[T|H]).`
*******************************************************
`is_symmetric(L):-  reverse(L,L).
`

**Comment by RedWn** [comment]
<details>
<summary>1.</summary>

`is_even_length([]).`
`is_even_length(L):-length(L,R),0 is mod(R,2).`

</details>

<details>
<summary>2.</summary>

`sum([],0).`
`sum([A|L],X):- sum(L,X1), X is A+X1. `

</details>

<details>
<summary>3.</summary>

`getlast([H],X):- X is H.`
`getlast([H|T],X):- getlast(T,X).`

</details>

<details>
<summary>4.</summary>

`getlast_but_one([H,H1|[]],X):- X is H.`
`getlast_but_one([H|T],X):- getlast(T,X).`

</details>
<details>
<summary>6.</summary>

'getm2([],M,M).'
'getm2([H|T],M,X):- H > M,getm2(T,H,X);getm2(T,M,X).'
'getm([H|T],X):- getm2([H|T],H,X).'
</details>

<details>
<summary>7.</summary>

`getn([H|T],0,X):- X is H.`
`getn([H|T],I,R):- I > 0,I1 is I-1,getn(T,I1,R).`
</details>

<details>
<summary>8.</summary>

`insert([],N,X,[X]).`
`insert([H|T],0,X,[X,H|T]).`
`insert([H|T],N,X,[H|L1]):-N1 is N-1,insert(T,N1,X,L1).`
</details>
<details>
<summary>9.</summary>

`split_at_index(L1,0,[],L1).`
`split_at_index([H|T],I,[H|T1],A2):- I1 is I-1,split_at_index(T,I1,T1,A2).`
</details>

<details>
<summary>12.</summary>

`getu([H|[]],L,[H|L]).`
`getu([H1|T1],L,[H1|T3]):- getu(T1,L,T3).`
</details>
<details>
<summary>13.</summary>

`geti([],L,[]).`
`geti([H|T],L,[H|T1]):- member(H,L),geti(T,L,T1).`
`geti([H|T],L,X):-geti(T,L,X).`
</details>
<details>
<summary>14.</summary>

`reverse([H|[]],L):- L is [H].`
`reverse([H|T],L):- reverse(T,[L|H]).`
</details>

**Comment by MuhammadSulaiman001** [comment]
Thank you guys, `count_elements_less_than/3` is missing 👀  

@OmamaEwer Could you please add the corresponding number for each exercise..

**Comment by AyahAlmasri21** [comment]
this code that solve the quize:

count_element_less([],X,0).

count_element_less([H|T],X,Z):- is_list(H),count_element_less(H,X,Z1),count_element_less(T,X,Z2),Z is Z1+Z2.
count_element_less([H|T],X,Z):-not( is_list(H)),count_element_less(T,X,Z1),(H<X-> Z is Z1+1; Z is Z1).

**Comment by MuhammadSulaiman001** [comment]
Hi @AyahAlmasri21, sure yes. Notice that if you combine `is_list(H)` and `not(is_list(H))` in one `(if -> then; else)` statement then you will get the same solution that I have submitted [here](https://github.com/MuhammadSulaiman001/prolog-lab/blob/79c9f1f5886bd1a0ee63fef6450a05b49bb3dca0/Lecture4-5.md?plain=1#L181).

**Comment by MuhammadSulaiman001** [comment]
Hi @SamiMhdAmin, I have tried this query `?- remove_duplicates([a,b,2,a,2,2,2], X).` the first result is true, but it allow pressing `;` and start giving wrong answers.. Could you improve it a bit, can you use the Cut to prevent getting more than one answer??
