### ISSUE TITLE
LECTURES 4-5 REVISITED

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [MuhammadSulaiman001/prolog-lab#7]
**`tag/2`**

Assign the correct label to a given point, the correct label = the label of the nearest point. 

Bonus: assign `unknown` in cases similar to `tag([3,-1], Label).`

```prolog
point([3,7], male).
point([3,-2], male).
point([0,0], female).
point([3,0], female).
point([3,3], female).
point([6,0], female).

% Sample queries
% ?- tag([4,6], Label).
%    Label = male.
% ?- tag([0,-10], Label).
%    Label = male.
% ?- tag([1,1], Label).
%    Label = female.
% ?- tag([3,0], Label).
%    Label = female.
% ?- tag([3,-1], Label). % bonus
%    Label = unkown.
```

**Comment by HasanMothaffar** [comment]
<details>
<summary>Solution:</summary>

```prolog

% We basically want to find the point that's closest to the input point
tag([InputX, InputY], Label) :-
    % Get a random point
    point([X, Y], ClosestPointLabel),
    
    \+ (
        % Get another random point
        point([A, B], _),

        % Make sure points are unique
        pair(X, Y) \= pair(A, B),

        % Calculate distances from the input point
        distance(pair(InputX, InputY), pair(X, Y), FirstDistance),
        distance(pair(InputX, InputY), pair(A, B), SecondDistance),


        % We're trying to find the point closest to the input point.
        %
        % If we find a point whose distance to the input point
        % is less than the distance of the first point,
        % then the first point is not a valid match.
        %
        % ==> Search for other solutions using backtrack.
        FirstDistance >= SecondDistance
    ),
    
    % Don't try other solutions. We found the perfect point.
    !,
    Label = ClosestPointLabel.

% We found two or more points whose distances from
% the input point are the same.
tag(_, Label) :- Label = "Unknown".
```

</details>

Credits to @Rami-Sabbagh for teaching me about the `\+` operator.

**Comment by MuhammadSulaiman001** [comment]
Hi @HasanMothaffar, brilliant, I got it, here are a few things to note:

1. Fix: The `distance/3` rule is missing, it could be 
```prolog
distance(pair(InputX, InputY), pair(X, Y), Res) :-
    T is (InputX - X) * (InputX - X) + (InputY - Y) * (InputY - Y), sqrt(T, Res).
```
2. Optimization: ` distance(pair(InputX, InputY), pair(X, Y), FirstDistance),` is recalculated over and over, so it could be written before the `\+` to be calculated only once.
3. Refactoring: The idea of your solution is to hold a base point and compare it against every other point in the database, so you could place the Cut `!` before the `\+` saying: "give me one point, cut, start the search".
4. I will keep this thread open for a while, waiting for another interesting solutions 😺

**Comment by MuhammadSulaiman001** [comment]
I will keep this thread open for a while, waiting for another interesting solutions 😺

**Comment by MuhammadSulaiman001** [comment]
Ok guys, here we are after [Lecture7](../blob/master/Lecture6-7.md).

So you need only one pass over the points to get the correct tag, I suggest using the following techniques to get another two solutions to this problem:

1. Using dynamics (`assert`, `retract`).
2. Using  Lists (`findall/3`)

good luck with that 😄

**Comment by Salims97** [comment]
```prolog
% facts


point([3,7], male).
point([3,-2], male).
point([0,0], female).
point([3,0], female).
point([3,3], female).
point([6,0], female).
```
### Points
```
point([X,Y] , R) :-
(
    X = 3 ,Y > -25, Y < 7 ->  Y1 is Y + 1,point([3,Y1], R)   ;

(   X = 3 ,Y < 25, Y >= 0 ->  Y2 is Y - 1,point([3,Y2], R) ) ;

(   X > -25 ,X  <   0, Y =  0 ->  X1 is X + 1,point([X1,0], R) ) ;
(   X <  25 ,X  >=  0, Y =  0 ->  X2 is X - 1,point([X2,0], R) ) ;


(   X > 3 -> point([3,Y],R) ) ; (Y > 0,Y =:=  3 , Y =:= 7 -> point([X,0],R));
(   X < 3 -> point([3,Y],R) ) ; (Y < 0,Y =:= -2 ->           point([X,0],R))


).

```

**Comment by MuhammadSulaiman001** [comment]
Hi @Salims97, the main issue with your solution is that it is not general, it won't work for any given set of points, for example, If I change the dataset to something like:

```
point([1000,70], female).
point([0,12], female).
point([-201,252], male).
```

then your solution won't work, right? you should not mention any real x,y values in your code.. look at the [solution above](https://github.com/MuhammadSulaiman001/prolog-lab/issues/7#issuecomment-1140468553) as an example.
